using MCRA.Data.Management.RawDataWriters;
using MCRA.General.Action.Settings;

namespace MCRA.Simulation.Actions.SingleValueNonDietaryExposures {

    public sealed class SingleValueNonDietaryExposuresOutputWriter {

        /// <summary>
        /// Writes the output data generated by a dietary exposures action to the provided raw data writer.
        /// </summary>
        public void WriteOutputData(ProjectDto project, ActionData data, SingleValueNonDietaryExposuresActionResult result, IRawDataWriter rawDataWriter) {
        }
    }
}
