using MCRA.Data.Management.RawDataWriters;
using MCRA.General.Action.Settings.Dto;

namespace MCRA.Simulation.Actions.SingleValueDietaryExposures {

    public sealed class SingleValueDietaryExposuresOutputWriter {

        /// <summary>
        /// Writes the output data generated by a dietary exposures action to the provided raw data writer.
        /// </summary>
        /// <param name="project"></param>
        /// <param name="data"></param>
        /// <param name="result"></param>
        /// <param name="rawDataWriter"></param>
        public void WriteOutputData(ProjectDto project, ActionData data, SingleValueDietaryExposuresActionResult result, IRawDataWriter rawDataWriter) {
            //var rawDataConverter = new RawDietaryExposuresDataConverter();
            //var exposureStatistics = getExposureStatistics(project, data, result);
            //if (exposureStatistics != null) {
            //    var rawData = rawDataConverter.ToRaw(exposureStatistics, project.OutputDetailSettings.SelectedPercentiles);
            //    rawDataWriter.Set(rawData);
            //}
        }
    }
}
