using MCRA.Data.Management.RawDataWriters;
using MCRA.General.Action.Settings;

namespace MCRA.Simulation.Actions.HbmSingleValueExposures {

    public sealed class HbmSingleValueExposuresOutputWriter {

        /// <summary>
        /// Writes the output data generated by a Single value HBM concentrations action to the provided raw data writer.
        /// </summary>
        /// <param name="project"></param>
        /// <param name="data"></param>
        /// <param name="result"></param>
        /// <param name="rawDataWriter"></param>
        public void WriteOutputData(
            ProjectDto project,
            ActionData data,
            HbmSingleValueExposuresActionResult result,
            IRawDataWriter rawDataWriter
        ) {
        }
    }
}
